name: ftp-deploy

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets["ftp.nacho-rodriguez.com"] }}
        username: ${{ secrets["nacho@nacho-rodriguez.com"] }}
        password: ${{ secrets["73?KvOtHe_76P"] }}
        local-dir: dist
        remote-dir: /home/perroagu/public_html/nacho-rodriguez.com
