name: setup-node

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
