export default {
  data() {
    return {
      portfolios: [
        {
          id: 1,
          img: require(`@/assets/images/portfolio/oversea.jpg`),
          logo: require(`@/assets/images/portfolio/OverseaLogo.png`),
          title: "OVERSEA - APP DE GESTIÓN",
          project:
            "Aplicación web para gestión de compras y existencias de la empresa, con login y roles diversos, alta de usuarios, clientes, proveedores, artículos, etc., Tablas de consulta, edición y eliminación de registros, exportaciones a Excel, hojas dse detalle con gráficas y estadísticas diversas. Control de existencias de diferentes almacenes.",
          client: "Oversea Atlantic Fish, S.L. Empresa dedicada a la importación y exportación de productos del mar congelados.",
          language: "HTML, CSS, SASS, JavaScript, Vue.js, C#, MySql",
          preview: "Oversea_AppDemo",
          previewLink: "https://oversea.siliconvalleyvigo.com/",
          // USUARIO: nacho@siliconvalleyvigo.com; CONTRASEÑA: 7777
          credentials: "Debido a las políticas de protección de datos el acceso a la aplicación está restringido. Puedes ",
          access: "enviarme un mensaje",
          credentials2: " y te facilitaré unas credenciales para acceder.",
        },
        {
          id: 2,
          img: require(`@/assets/images/portfolio/imasp.jpg`),
          logo: require(`@/assets/images/portfolio/imaspLogo.png`),
          title: "IMASP - APP DE GESTIÓN",
          project: "Aplicación web de gestión de técnicos y contratos, con login y roles diversos, alta y mantenimiento de empleados y de contratos, formularios y gestión de gastos, cargas de trabajo, etc.",
          client: "Ingeniería y Prevención de Riesgos, S.L. Empresa dedicada al control de obras públicas y privadas, con técnicos que supervisan la observación de las normas de seguridad en los lugares de trabajo. App en español e inglés, pudiéndose cambiar de idioma en cualquier momento.",
          language: "HTML, CSS, SASS, JavaScript, Vue.js, C#, MySql",
          preview: "IMASP_AppDemo",
          previewLink: "https://testingimasp.siliconvalleyvigo.com/",
          // USUARIO: master@siliconvalleyvigo.com; CONTRASEÑA: 7777
          credentials: "Debido a las políticas de protección de datos el acceso a la aplicación está restringido. Puedes ",
          access: "enviarme un mensaje",
          credentials2: " y te facilitaré unas credenciales para acceder.",
        },
        {
          id: 3,
          img: require(`@/assets/images/portfolio/anem.jpg`),
          logo: require(`@/assets/images/portfolio/logoAnem.svg`),
          title: "ANEM - APP DE GESTIÓN",
          project: "Aplicación web para gestión de envíos postales certificados, con login y roles diversos, permite subir archivos EXCEL y SICER con las cartas a repartir, asignarlas a un repartidor y hacer un seguimiento. Existe también una parte de entrega en dónde dicho repartidor lista sus envíos y registra su firma y la del destinatario al entregar la carta. La aplicación está disponible también en formato PWA para ser descargada en dispositivos móviles.",         
          client: "NETCOM Servicios Informáticos",
          language: "HTML, CSS, SASS, JavaScript, Vue.js, C#, MySql",
          preview: "ANEM_AppDemo",
          previewLink: "https://anem.siliconvalleyvigo.com/",
          // USUARIO: info@siliconvalleyvigo.com; CONTRASEÑA: 7777
          credentials: "Debido a las políticas de protección de datos el acceso a la aplicación está restringido. Puedes ",
          access: "enviarme un mensaje",
          credentials2: " y te facilitaré unas credenciales para acceder.",
        },
        {
          id: 4,
          img: require(`@/assets/images/portfolio/sofyweb.jpg`),
          logo: require(`@/assets/images/portfolio/logoSofyweb.png`),
          title: "SOFYWEB - MIGRACIÓN DE APP",
          project: "Migración de app de escritorio obsoleta a web. Aplicación totalmente nueva y adaptada a la nuevas tecnologías basada en una exitente de escritorio, clonando sus funcionalidades y creando otars nuevas.",
          client: "Sofycom",
          language: "HTML, CSS, SASS, JavaScript, Vue.js, C#, MySql",
          preview: "SOFYWEB_AppDemo",
          previewLink: "https://sofyweb.sofygest.es",
          credentials: "USUARIO: jose; EMPRESA: sofyweb; CONTRASEÑA: jose",
        },
        {
          id: 5,
          img: require(`@/assets/images/portfolio/osnor.jpg`),
          logo: require(`@/assets/images/portfolio/osnorLogo.png`),
          title: "ANEM - APP DE GESTIÓN",
          project: "App de gestión de obras portuarias que permite la importación de archivo Excel con datos de las obras y genera tablas y gráficas para el seguimiento de sus estados, pagos, etc.",
          client: "Osnor",
          language: "HTML, CSS, SASS, JavaScript, Vue.js, C#, MySql",
          preview: "OSNOR_AppDemo",
          previewLink: "https://osnor.siliconvalleyvigo.com/",
          // USUARIO: osnor@osnor.com; CONTRASEÑA: Osnor
          credentials: "USUARIO: osnor@osnor.com; CONTRASEÑA: Osnor",
        },
        {
          id: 6,
          img: require(`@/assets/images/portfolio/mandopro.jpg`),
          logo: require(`@/assets/images/portfolio/rodaproLogo.svg`),
          title: "RODAPRO - DEMO DE CUADRO DE MANDOS INTEGRAL",
          project: "Página web con demo funcional de cuadro de mandos para su presentación y comercialización.",
          client: "Rodapro",
          language: "HTML, CSS, SASS, JavaScript, Vue.js",
          preview: "MANDOPRO_Demo",
          previewLink: "https://cuadrodemandos.rodapro.es/",
          credentials: "No se requieren credenciales.",
        },
        {
          id: 7,
          img: require(`@/assets/images/portfolio/project-7.jpg`),
          title: "MOCKUP PROJECT",
          project: "Website",
          client: "Pexels",
          language: "Adobe Photoshop",
          preview: "www.pexels.com",
          previewLink: "https://www.pexels.com/",
        },
        {
          id: 8,
          img: require(`@/assets/images/portfolio/project-8.jpg`),
          title: "FACEBOOK PROJECT",
          project: "Shoot",
          client: "Facebook",
          language: "Reactjs",
          preview: "www.facebook.com",
          previewLink: "https://www.facebook.com/ibthemes",
        },
        {
          id: 9,
          img: require(`@/assets/images/portfolio/project-9.jpg`),
          title: "LINKEDIN PROJECT",
          project: "Website",
          client: "Linkedin",
          language: "Vue 3",
          preview: "www.linkedin.com",
          previewLink:
            "https://www.linkedin.com/in/ib-themes-company-469408207/recent-activity/shares/",
        },
      ],
    };
  },
};
